openapi: 3.0.0
info:
  title: Auction API
  version: 1.0.0
produces:
  - application/json
paths:
  /auctions:
    post:
      summary:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                endTime:
                  type: string
                  format: date-time
      responses:
        201:
          description: Auction created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string

  /auctions/{id}/bid:
    post:
      summary: Place a bid on an auction
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                value:
                  type: number

  /auctions/{id}:
    get:
      summary: Get an auction by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    type: string
                  id:
                    type: string
                  endTime:
                    type: string
                    format: date-time
                  winnerUsername:
                    type: string
                    nullable: true

security:
  - basicAuth: []
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
